version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - "27017:27017"
    command: mongod --smallfiles --logpath=/dev/null # --quiet
  eureka:
    image: eureka:latest
    container_name: "eureka-server"
    restart: always
    ports:
      - "8761:8761"
  auth:
    image: auth:latest
    restart: always
    depends_on:
      - mongodb
      - eureka
    links:
      - mongodb
      - eureka
    ports:
      - "9100:9100"
  library:
    image: library:latest
    restart: always
    depends_on:
      - mongodb
      - eureka
    links:
      - mongodb
      - eureka
    ports:
      - "8080:8080"
  zuul:
    image: zuul:latest
    restart: always
    depends_on:
      - library
      - eureka
      - auth
    links:
      - eureka
    ports:
      - "8762:8762"