spring:
  application:
    name: library-service
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

jms:
  sender:
    broker-url: tcp://localhost:61616